cle_discount_accueil:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/accueil.yml"
    prefix:   /accueil
    
cle_discount_catalogue:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/catalogue.yml"
    prefix:   /catalogue
    
cle_discount_cataloguepro:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/cataloguepro.yml"
    prefix:   /cataloguepro
    
cle_discount_contact:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

cle_discount_commande:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/commande.yml"
    prefix:   /commande