cle_discount_accueil:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/accueil.yml"
    prefix:   /accueil
    
cle_discount_catalogue:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/catalogue.yml"
    prefix:   /catalogue
    
cle_discount_cataloguepro:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/cataloguepro.yml"
    prefix:   /cataloguepro
    
cle_discount_contact:
    resource: "@CleDiscountCatalogueBundle/Resources/config/routing/contact.yml"
    prefix:   /contact

skyrim_alchimie:
    resource: "@SkyrimAlchimieBundle/Resources/config/routing.yml"
    prefix:   /skyrim

sdz_blog:
    resource: "@SdzBlogBundle/Resources/config/routing.yml"
    prefix:   /sdzblog

junior_etudiant:
    resource: "@JuniorEtudiantBundle/Resources/config/routing/etudiant.yml"
    prefix:   /etudiant
    
junior_gestion:
    resource: "@JuniorEtudiantBundle/Resources/config/routing/gestion.yml"
    prefix:   /gestion

#je_student:
#    resource: "@JEStudentBundle/Resources/config/routing.yml"
#    prefix:   /
#    
#je_blog:
#    resource: "@JEBlogBundle/Resources/config/routing.yml"
#    prefix:   /blog

fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profile.xml"
    prefix: /profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.xml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.xml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.xml"
    prefix: /profile

