cle_contact_contact:
    pattern:  /contact
    defaults: { _controller: CleDiscountCatalogueBundle:contact:contact }
    
cle_contact_mentions:
    pattern:  /mentions
    defaults: { _controller: CleDiscountCatalogueBundle:contact:mentions }
    
cle_contact_recrutement:
    pattern:  /recrutement
    defaults: { _controller: CleDiscountCatalogueBundle:contact:recrutement }
    
cle_contact_partenaires:
    pattern:  /partenaires
    defaults: { _controller: CleDiscountCatalogueBundle:contact:partenaires }
    
cle_contact_referencement:
    pattern:  /referencement
    defaults: { _controller: CleDiscountCatalogueBundle:contact:referencement }
    
cle_contact_serviceclient:
    pattern:  /contact/serviceclient
    defaults: { _controller: CleDiscountCatalogueBundle:contact:serviceclient }
    
cle_contact_servicecommercial:
    pattern:  /contact/servicecommercial
    defaults: { _controller: CleDiscountCatalogueBundle:contact:servicecommercial }  
  